name: Deploy Gradio to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # (Optional) quick sanity test so broken commits don't deploy
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Smoke test
        run: |
          python - <<'PY'
          import importlib.util, sys, pathlib
          p = pathlib.Path("app.py")
          assert p.exists(), "app.py missing at repo root"
          # Basic import of gradio + file
          import gradio as gr
          spec = importlib.util.spec_from_file_location("app", str(p))
          m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
          print("App import OK")
          PY

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: hlmshkr
          SPACE_NAME: gpu-sizing-calculator
        run: |
          git lfs install
          # add HF Space as a remote and push main
          git remote add space https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/$HF_USER/$SPACE_NAME || true
          git push space HEAD:main --force
